# services:
#   backend:
#     build: ./InsightApps
#     volumes:
#       - ./InsightApps:/app
#     ports:
#       - "8000:8000"
#     # command: python /app/manage.py runserver 0.0.0.0:8000

#   frontend:
#     build: ./InsightApps-Angular
#     ports:
#       - "8080:80"
#     volumes:
#       - ./dist/InsightApps-Angular:/frontend:/usr/share/nginx/html


##################################
# version: '3.8'

services:
  backend:
    build:
      context: ./InsightApps
      args:
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./InsightApps:/app
    ports:
      - "8000:8000"
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000"


  frontend:
    build: ./InsightApps-Angular
    ports:
      - "8080:80"
    volumes:
      - ./dist/InsightApps-Angular:/frontend:/usr/share/nginx/html

