# Generated by Django 5.0.4 on 2024-09-02 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('qbuserid', models.CharField(blank=True, db_column='quickbooks_user_id', max_length=1000, null=True)),
                ('salesuserid', models.CharField(blank=True, db_column='salesforce_user_id', max_length=1000, null=True)),
                ('tokentype', models.CharField(blank=True, db_column='token_type', max_length=100, null=True)),
                ('accesstoken', models.CharField(blank=True, db_column='access_token', max_length=1800, null=True)),
                ('refreshtoken', models.CharField(blank=True, db_column='refresh_token', max_length=1800, null=True)),
                ('idtoken', models.CharField(blank=True, db_column='id_token', max_length=1800, null=True)),
                ('realm_id', models.CharField(blank=True, db_column='realm_id', max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, db_column='display_name', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 10, 46, 58, 853901))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 10, 46, 58, 853901))),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 11, 46, 58, 852901))),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
    ]
