# Generated by Django 5.0.4 on 2024-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eeid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('business_unit', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('hire_date', models.DateTimeField()),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
