sheetquerysets_list=["""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT COUNT("EmpID") AS "count(EmpID)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table WHERE "Gender" IN (''Female'', ''Male'')', '{datetime}', '{datetime}', '[]', '[''count(EmpID)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table', '{datetime}', '{datetime}', '[]', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
(datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL,{querysets_id}, {user_id}, NULL, '[]', 'SELECT COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table WHERE "Attrition" IN (''No'')', '{datetime}', '{datetime}', '[]', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "EducationField", COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table WHERE "Attrition" IN (''Yes'') GROUP BY "EducationField"', '{datetime}', '{datetime}', '['' "EducationField"'']', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",

"""INSERT INTO public."sheetFilter_querysets"
(datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "JobRole", COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table GROUP BY "JobRole"', '{datetime}', '{datetime}', '['' "JobRole"'']', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "SalarySlab", COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table WHERE "Attrition" IN (''Yes'') GROUP BY "SalarySlab"', '{datetime}', '{datetime}', '['' "SalarySlab"'']', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",

"""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "AgeGroup", COUNT("Attrition") AS "count(Attrition)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table WHERE "Attrition" IN (''Yes'') GROUP BY "AgeGroup"', '{datetime}', '{datetime}', '['' "AgeGroup"'']', '[''count(Attrition)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
(datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "PerformanceRating", COUNT("EmployeeCount") AS "count(EmployeeCount)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table GROUP BY "PerformanceRating"', '{datetime}', '{datetime}', '['' "PerformanceRating"'']', '[''count(EmployeeCount)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
(datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "BusinessTravel", COUNT("EmployeeCount") AS "count(EmployeeCount)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table GROUP BY "BusinessTravel"', '{datetime}', '{datetime}', '['' "BusinessTravel"'']', '[''count(EmployeeCount)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";""",


"""INSERT INTO public."sheetFilter_querysets"
( datasource_querysetid, queryset_id, user_id, server_id, filter_id_list, custom_query, created_at, updated_at, "columns", "rows", file_id)
VALUES( NULL, {querysets_id}, {user_id}, NULL, '[]', 'SELECT "Gender", COUNT("EmployeeCount") AS "count(EmployeeCount)" FROM (SELECT "HRAnalytics"."EmpID" AS "EmpID", "HRAnalytics"."Age" AS "Age", "HRAnalytics"."AgeGroup" AS "AgeGroup", "HRAnalytics"."Attrition" AS "Attrition", "HRAnalytics"."BusinessTravel" AS "BusinessTravel", "HRAnalytics"."DailyRate" AS "DailyRate", "HRAnalytics"."Department" AS "Department", "HRAnalytics"."DistanceFromHome" AS "DistanceFromHome", "HRAnalytics"."Education" AS "Education", "HRAnalytics"."EducationField" AS "EducationField", "HRAnalytics"."EmployeeCount" AS "EmployeeCount", "HRAnalytics"."EmployeeNumber" AS "EmployeeNumber", "HRAnalytics"."EnvironmentSatisfaction" AS "EnvironmentSatisfaction", "HRAnalytics"."Gender" AS "Gender", "HRAnalytics"."HourlyRate" AS "HourlyRate", "HRAnalytics"."JobInvolvement" AS "JobInvolvement", "HRAnalytics"."JobLevel" AS "JobLevel", "HRAnalytics"."JobRole" AS "JobRole", "HRAnalytics"."JobSatisfaction" AS "JobSatisfaction", "HRAnalytics"."MaritalStatus" AS "MaritalStatus", "HRAnalytics"."MonthlyIncome" AS "MonthlyIncome", "HRAnalytics"."SalarySlab" AS "SalarySlab", "HRAnalytics"."MonthlyRate" AS "MonthlyRate", "HRAnalytics"."NumCompaniesWorked" AS "NumCompaniesWorked", "HRAnalytics"."Over18" AS "Over18", "HRAnalytics"."OverTime" AS "OverTime", "HRAnalytics"."PercentSalaryHike" AS "PercentSalaryHike", "HRAnalytics"."PerformanceRating" AS "PerformanceRating", "HRAnalytics"."RelationshipSatisfaction" AS "RelationshipSatisfaction", "HRAnalytics"."StandardHours" AS "StandardHours", "HRAnalytics"."StockOptionLevel" AS "StockOptionLevel", "HRAnalytics"."TotalWorkingYears" AS "TotalWorkingYears", "HRAnalytics"."TrainingTimesLastYear" AS "TrainingTimesLastYear", "HRAnalytics"."WorkLifeBalance" AS "WorkLifeBalance", "HRAnalytics"."YearsAtCompany" AS "YearsAtCompany", "HRAnalytics"."YearsInCurrentRole" AS "YearsInCurrentRole", "HRAnalytics"."YearsSinceLastPromotion" AS "YearsSinceLastPromotion", "HRAnalytics"."YearsWithCurrManager" AS "YearsWithCurrManager" FROM "main"."HRAnalytics" AS "HRAnalytics") temp_table GROUP BY "Gender"', '{datetime}', '{datetime}', '['' "Gender"'']', '[''count(EmployeeCount)'']', {file_detail_id}) RETURNING "Sheetqueryset_id";"""]






sheet_saving = ["""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 24, NULL,{querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-54-562023280.txt', '2024-08-25 17:03:39.457', '2024-08-25 17:24:56.692', 'insightapps/sheetdata/2024-08-25_11-54-562023280.txt', 'Employee performance rating count', '[]', {id}, '<p><strong>Employee performance rating count</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 24, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-35-062023280.txt', '2024-08-25 17:05:06.205', '2024-08-25 11:35:06.206', 'insightapps/sheetdata/2024-08-25_11-35-062023280.txt', 'Employee Travel Details', '[]', {id}, '<p><strong>Employee Travel Details</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES({user_id}, 6, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-55-062023280.txt', '2024-08-25 17:11:03.202', '2024-08-25 17:25:07.101', 'insightapps/sheetdata/2024-08-25_11-55-062023280.txt', 'Gender Wise Employee Count', '[]', {id}, '<p><strong>Gender Wise Employee Count</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 10, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-55-132023280.txt', '2024-08-24 17:59:37.999', '2024-08-25 17:25:14.127', 'insightapps/sheetdata/2024-08-25_11-55-132023280.txt', 'Attrition by education', '[]', {id}, '<p><strong>Attrition by education</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 3, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-55-202023280.txt', '2024-08-24 18:16:44.837', '2024-08-25 17:25:21.039', 'insightapps/sheetdata/2024-08-25_11-55-202023280.txt', 'Attrition by salary slab', '[]',  {id}, '<p><strong>Attrition by salary slab</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 6, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-55-282023280.txt', '2024-08-24 18:22:10.963', '2024-08-25 17:25:28.720', 'insightapps/sheetdata/2024-08-25_11-55-282023280.txt', 'Attrition by Age group', '[]', {id}, '<p><strong>Attrition by Age group</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 3, NULL,  {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_11-55-582023280.txt', '2024-08-24 18:05:21.092', '2024-08-25 17:25:59.051', 'insightapps/sheetdata/2024-08-25_11-55-582023280.txt', 'Attrition by Job Role', '[]', {id}, '<p><strong>Attrition by Job Role</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 25, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_12-09-332023280.txt', '2024-08-24 17:53:05.757', '2024-08-25 17:39:33.861', 'insightapps/sheetdata/2024-08-25_12-09-332023280.txt', 'Attrition', '[]', {id}, '<p><strong>Attrition</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 25, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_12-09-422023280.txt', '2024-08-24 17:55:15.995', '2024-08-25 17:39:42.503', 'insightapps/sheetdata/2024-08-25_12-09-422023280.txt', 'Active Employees', '[]', {id}, '<p><strong>Active Employees</strong></p>', {file_detail_id}) RETURNING "sheet_id";""",

"""INSERT INTO public.sheet_data
( user_id, chart_id, server_id, queryset_id, sheet_data_source, created_at, updated_at, sheet_data_path, sheet_name, filter_ids, sheetfilter_querysets_id, sheet_tag_name, file_id)
VALUES( {user_id}, 25, NULL, {querysets_id}, 'https://haskmedia.s3.amazonaws.com/insightapps/sheetdata/2024-08-25_13-03-392023280.txt', '2024-08-24 17:50:43.853', '2024-08-25 18:33:39.727', 'insightapps/sheetdata/2024-08-25_13-03-392023280.txt', 'Total Employees', '[663]', {id}, '<p><strong>Total Employees</strong></p>', {file_detail_id}) RETURNING "sheet_id";"""]